name: vy_dart_meme
description: Dart Message Memory. A way of storing translations for dart.
version: 0.2.0
homepage: https://github.com/giorgiofran/vy_dart_meme

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  vy_language_tag: ^0.2.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.4
