name: vy_dart_meme
version: 0.1.8
description: Dart Message Memory. A way of storing translations for dart.
homepage: "https://github.com/giorgiofran/vy_dart_meme"

dependencies:
  vy_language_tag: 0.1.5

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0

environment:
  sdk: ">=2.7.1 <3.0.0"
