name: vy_dart_meme
description: Dart Message Memory. A way of storing translations for dart.
version: 0.1.5
homepage: https://github.com/giorgiofran/vy_dart_meme

environment:
  sdk: '>=2.7.1 <3.0.0'

dependencies:
  vy_language_tag: ^0.1.3

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
